# Generated by Django 4.0.6 on 2022-08-11 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('com_linkedin__TT', '0002_rename_loaded_linkpeople_executed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkpeople',
            name='executor',
            field=models.CharField(default=None, max_length=120),
        ),
    ]
