# Generated by Django 4.0.6 on 2022-08-11 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('com_linkedin__TT', '0003_linkpeople_executor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkpeople',
            name='executor',
            field=models.CharField(default=None, max_length=120, null=True),
        ),
    ]
