# Generated by Django 4.0.6 on 2022-08-11 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('com_linkedin__TT', '0004_alter_linkpeople_executor'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkpeople',
            name='sended_moment',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
