# Generated by Django 4.0.6 on 2022-08-27 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('com_linkedin__TT', '0005_linkpeople_sended_moment'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkpeople',
            name='error_code',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
